<a href="https://colab.research.google.com/github/nicoweber95/DeepRitzMethod/blob/master/Deep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We want solve the following Dirichlet boundary problem: \\
$-\Delta u = 0$ in $\Omega$ \\
$u = 0$ in $\partial \Omega$ \\
$\Omega$ = \{ x  $\in$ $\mathbb{R}^n$  | $\sum_{i=1}^{n} x_i^2 \leq 1$} \\
exact solution: $\frac{1}{2n}(\sum_{i=1}^{n} x_i^2 -1 )$ 

In [0]:
#from __future__import absolute_import, division, print_function, unicode_literals
#example 3.1: The Poisson equation in two dimensions
try:
  # default tensorflow is 1.15
  %tensorflow_version 2.x
except Exception:
  pass
import numpy as np
from numpy import linalg as LA
import itertools as it
import math
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import tensorflow as tf
# backend: create own activation functions, layers
from tensorflow.keras import backend as K 
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras import Model

class RitzNet(Model):
  def __init__(self,m,dim):
    super(RitzNet, self).__init__()
    self.m = m
    self.dim = dim
# test example for dimension 2,3 and 8; For later: make dimension variabel
    if self.dim == 2:
      self.l0 = Flatten()
      self.l1 = Dense(m, activation = a_three)
      self.l2 = Dense(m, activation = a_three)
      self.l3 = Dense(m, activation = a_three)
    elif seld.dim ==3:
      self.l1 = Dense(m, activation = a_three)
      self.l2 = Dense(m, activation = a_three)
      self.l3 = Dense(m, activation = a_three)
      self.l4 = Dense(m, activation = a_three)
    elif self.dim == 8:
      self.l1 = Dense(m, activation = a_three)
      self.l2 = Dense(m, activation = a_three)
      self.l3 = Dense(m, activation = a_three)
      self.l4 = Dense(m, activation = a_three)
      self.l5 = Dense(m, activation = a_three)
  def call(self,x):
    if self.dim == 2:
      print(x)
      x = self.l0(x)
      x = self.l1(x)
      x = self.l2(x)
      return  self.l3(x)
    elif seld.dim ==3:
      x = self.l1(x)
      x = self.l2(x)
      x = self.l3(x)
      return  self.l4(x)
    elif self.dim == 8:
      x = self.l1(x)
      x = self.l2(x)
      x = self.l3(x)
      x = self.l4(x)
      return  self.l5(x)

#define own activation function 
def a_three(x):
  return K.ReLU 
  #return K.ReLU(np.power(x,3))

In [0]:
def exact_function(x,n):
  func = np.zeros(1)
  for i in range(0,n):
    func += x[i]**2
  func += -1
  func /= (2*n)
  return func
  


In [0]:
# question: cann loss fm/keras-team/keras/issues/2121#issuecomment-214551349
def penalized_loss
#(unction only take two argumensts
# see https://github.cosample_strategy):
    def loss(y_true, y_pred):
        return K.mean(K.square(y_pred - y_true) - K.square(y_true - noise), axis=-1)
    return loss


input1 = Input(batch_shape=(batch_size, timesteps, features))
lstm =  LSTM(features, stateful=True, return_sequences=True)(input1)
output1 = TimeDistributed(Dense(features, activation='sigmoid'))(lstm)
output2 = TimeDistributed(Dense(features, activation='sigmoid'))(lstm)
model = Model(input=[input1], output=[output1, output2])
model.compile(loss=[penalized_loss(noise=output2), penalized_loss(noise=output1)], optimizer='rmsprop')
def cal

In [0]:
def custom_loss(model,dimension,x_in,x_out,lam):
  dim_in = x_in.shape[0]
  dim_out = x_out.shape[0]
  
  loss = np.zeros(1)
  regularization = np.zeros(1)
  eps = 0.0001
  for j in it.product(*map(range,x_in.shape[1:])):
    #y = model([x_in[i][j] for i in range(dim_in)],dimension)
    p = [x_in[i][j] for i in range(dim_in)]
    p = np.array(p)
    print(p.shape)
    #hier ist der Fehler iwo
    y = model([x_in[i][j] for i in range(dim_in)])
    
    x_grad = np.zeros(dim_in)
    for i in range(dim_in):
      x_grad[i] = (model(x_in[i][j]+eps) - y[i])/ eps
    loss += 0.5*(np.sum([x**2 for x in x_grad ]) - y)
  loss /= dim_in 
  for j in it.product(*map(range,x_out.shape[1:])):
    y = model([x_in[i][j] for i in range(dim_out)],dimension)
    regularization += lam*y**2
  regularization /= dim

In [0]:
#https://towardsdatascience.com/tensorflow-2-0-create-and-train-a-vanilla-cnn-on-google-colab-c7a0ac86d61b
def grad(model,x_in,x_out):
  x_in = np.array(x_in)
  x_out = np.array(x_out)
  print(x_in.shape)
  with tf.GradientTape() as tape:
    #prediction1 = model(x_in)
    #prediction2 = model(x_out)
    loss = custom_loss(model,3,x_in,x_out,500)
  return loss, tape.gradient(loss, model.trainable_variables)
  #optimizer = tf.keras.optimizers.SGD
  #optimizer.apply_gradients(zip(gradients, model.trainable_variables))

In [0]:
def data(x_in,x_out):
  dimension = x_in.shape[0]
  y_in  = np.zeros(x_in.shape[1:])
    #for i in range(dimension):
  for j in it.product(*map(range,x_in.shape[1:])):
    print(42)
    print([x_in[i][j] for i in range(dimension)])
    y_in[j] = exact_function([x_in[i][j] for i in range(dimension)],dimension)
    print(y_in[j])

In [43]:
## Note: Rerunning this cell uses the same model variables
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
tf.keras.backend.set_floatx('float64')
# Keep results for plotting
train_loss_results = []
train_accuracy_results = []
[x_in,x_out]= grid_sampling(0,2,2,3)
print(x_in)
num_epochs = 201
model = RitzNet(10,2)
for epoch in range(num_epochs):
  epoch_loss_avg = tf.keras.metrics.Mean()
  epoch_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

  # Training loop - using batches of 32
  for x, y in zip(x_in,x_out):
    # Optimize the model
    print(x)
    x = np.array(x)
    y = np.array(y)
    #print(x.shape)
    loss_value, grad = grad(model, [x[0][0],x[1][0]], [y[0][0],y[1][0]])
    optimizer.apply_gradients(zip(grad, model.trainable_variables))

    # Track progress
    epoch_loss_avg(loss_value)  # Add current batch loss
    # Compare predicted label to actual label
    epoch_accuracy(y, model(x))

  # End epoch
  train_loss_results.append(epoch_loss_avg.result())
  train_accuracy_results.append(epoch_accuracy.result())

  if epoch % 50 == 0:
    print("Epoch {:03d}: Loss: {:.3f}, Accuracy: {:.3%}".format(epoch,
                                                                epoch_loss_avg.result(),
                                                                epoch_accuracy.result()))

[[[-1.  0.]
  [-1.  0.]]

 [[-1. -1.]
  [ 0.  0.]]]
[[-1.  0.]
 [-1.  0.]]
(2,)
(2,)
[<tf.Tensor: id=585, shape=(), dtype=float64, numpy=-1.0>, <tf.Tensor: id=586, shape=(), dtype=float64, numpy=-1.0>]


ValueError: ignored

In [0]:
def grid_sampling(type,dim,n_in,n_b):
#type: 0: uniform sampling, 1: random sampling
#dim: dimension of domain
#n_in: number points in domain interior for each dimension ( n_in*dim all in all)
#n_out: number points on boundary for each dimension (n_out*dim all in all)
#idea boundary: take the boundary [-1,1]^dim and normalize to one
#example :x= grid_sampling(0,2,2,3)
#print(x[0])
#print(x[1])
#[array([[-1.,  0.],
 #      [-1.,  0.]]), array([[-1., -1.],
  #     [ 0.,  0.]])]
#[[[-0.70710678  0.          0.70710678]
 # [-1.          0.          1.        ]
  #[-0.70710678  0.          0.70710678]]

 #[[-0.70710678 -1.         -0.70710678]
 # [ 0.          0.          0.        ]
  #[ 0.70710678  1.          0.70710678]]]
  if type == 0:
    points = np.arange(-1,1,2/n_in)
    points_dim = [np.array(points) for i in range(1,dim+1)]
    x = np.meshgrid(*points_dim)
    x = np.asarray(x)
    points_b = np.linspace(-1.0,1.0,num = n_b )
    points_out = [points_b for i in range(1,dim+1)]
    points_out = np.meshgrid(*points_out)
    y = np.divide(points_out,LA.norm(points_out,axis =0),where=LA.norm(points_out,axis =0) !=0)
    y = np.asarray(y)
  elif type == 1:
    print('Hello')

  return [x,y];


In [24]:
[x,y]= grid_sampling(0,2,3,3)
#data(x[0],x[1])
print(x)
print(y)
#print(y[2][0,0,0])

[[[-1.         -0.33333333  0.33333333]
  [-1.         -0.33333333  0.33333333]
  [-1.         -0.33333333  0.33333333]]

 [[-1.         -1.         -1.        ]
  [-0.33333333 -0.33333333 -0.33333333]
  [ 0.33333333  0.33333333  0.33333333]]]
[[[-0.70710678  0.          0.70710678]
  [-1.          0.          1.        ]
  [-0.70710678  0.          0.70710678]]

 [[-0.70710678 -1.         -0.70710678]
  [ 0.          0.          0.        ]
  [ 0.70710678  1.          0.70710678]]]
